initialWaveNumber: 1
timeBetweenWavesSec: 7
enemyHealthMultiplierPerWave: 1.08
enemySpeedMultiplierPerWave: 1.02
enemyCountMultiplierPerWave: 1.10
enemyRewardMultiplierPerWave: 1.05
bossWaveFrequency: 10
bossId: circle_boss
initialEnemyTypes: [triangle_scout]
waveEnemyTypeUnlock:
  5: square_tank
  15: pentagon_healer
spawnPattern: standard_grid
