- id: triangle_scout
  shape: triangle
  baseHealth: 50
  baseSpeed: 40
  baseReward: 5
  collisionDamage: 10 # Added
  movementPattern: invader_standard
  collisionRadius: 15
  canShoot: false
- id: square_tank
  shape: square
  baseHealth: 150
  baseSpeed: 25
  baseReward: 15
  collisionDamage: 20 # Added
  movementPattern: invader_standard
  collisionRadius: 25
  canShoot: true
  shootConfig:
    projectileType: enemy_bullet
    cooldownMs: 1500
    damage: 5
    speed: 100
- id: pentagon_healer
  shape: pentagon
  baseHealth: 100
  baseSpeed: 30
  baseReward: 20
  collisionDamage: 5 # Added (lower for support?)
  movementPattern: invader_support
  collisionRadius: 20
  canShoot: false
  abilities:
    - type: heal_aura
      range: 100
      healPerSec: 5
- id: hexagon_bomber # New Enemy
  shape: hexagon
  baseHealth: 80
  baseSpeed: 60 # Faster dive
  baseReward: 25
  collisionDamage: 15
  movementPattern: bomber_dive # New pattern
  collisionRadius: 22
  canShoot: false # Doesn't shoot normally
  abilities:
    - type: death_bomb
      projectileType: enemy_bomb # Placeholder projectile type
      damage: 30
      radius: 50 # Placeholder for explosion radius if needed
- id: circle_boss
  shape: circle
  baseHealth: 2000
  baseSpeed: 20
  baseReward: 100
  collisionDamage: 50 # Added (higher for boss)
  movementPattern: boss_weaving
  collisionRadius: 50
  canShoot: true
  shootConfig:
    projectileType: enemy_laser
    cooldownMs: 800
    damagePerSec: 10
    range: 300
  abilities:
    - type: spawn_minions
      minionId: triangle_scout
      cooldownMs: 5000
      count: 3
