- id: triangle_scout
  shape: triangle
  baseHealth: 50
  baseSpeed: 40
  baseReward: 5
  scoreValue: 10 # Added
  collisionDamage: 10 # Added
  movementPattern: invader_standard
  collisionRadius: 8 # Increased from 5
  canShoot: false
- id: square_tank
  shape: square
  baseHealth: 150
  baseSpeed: 25
  baseReward: 15
  scoreValue: 30 # Added
  collisionDamage: 20 # Added
  movementPattern: invader_standard
  collisionRadius: 12 # Increased from 8
  canShoot: true
  shootConfig:
    projectileType: enemy_bullet
    cooldownMs: 4500 # Increased from 1500 (1500 * 3)
    damage: 5
    speed: 100
    # Visuals
    visualShape: ellipse
    visualWidth: 6
    visualHeight: 6
    visualColor: '0xffa500' # Orange
- id: pentagon_healer
  shape: pentagon
  baseHealth: 100
  baseSpeed: 30
  baseReward: 20
  scoreValue: 40 # Added
  collisionDamage: 5 # Added (lower for support?)
  movementPattern: invader_support
  collisionRadius: 11 # Increased from 7
  canShoot: false
  abilities:
    - type: heal_aura
      range: 100
      healPerSec: 5
- id: hexagon_bomber # New Enemy
  shape: hexagon
  baseHealth: 80
  baseSpeed: 60 # Faster dive
  baseReward: 25
  scoreValue: 50 # Added
  collisionDamage: 15
  movementPattern: bomber_dive # New pattern
  collisionRadius: 11 # Increased from 7
  canShoot: false # Doesn't shoot normally
  abilities:
    - type: death_bomb
      projectileType: enemy_bomb # Placeholder projectile type
      damage: 30
      radius: 50 # Placeholder for explosion radius if needed
      # Note: Visuals for death_bomb projectile handled by type in handler for now
- id: diamond_strafer # New Enemy
  shape: diamond
  baseHealth: 70
  baseSpeed: 150 # Fast horizontal speed
  baseReward: 30
  scoreValue: 60 # Added
  collisionDamage: 15
  movementPattern: strafe_horizontal # New pattern
  collisionRadius: 9 # Increased from 6
  canShoot: true
  shootConfig:
    projectileType: enemy_bullet_fast # Placeholder, maybe faster bullet
    cooldownMs: 3000 # Increased from 1000 (1000 * 3)
    damage: 8
    speed: 180
    # Visuals
    visualShape: rectangle
    visualWidth: 5
    visualHeight: 5
    visualColor: '0xff8c00' # Dark Orange
- id: circle_boss
  shape: circle
  baseHealth: 2000
  baseSpeed: 20
  baseReward: 100
  scoreValue: 200 # Added
  collisionDamage: 50 # Added (higher for boss)
  movementPattern: boss_weaving
  collisionRadius: 23 # Increased from 15
  canShoot: true
  shootConfig:
    projectileType: enemy_laser
    cooldownMs: 2400 # Increased from 800 (800 * 3)
    damagePerSec: 10
    range: 300
    # Visuals
    visualShape: rectangle
    visualWidth: 4
    visualHeight: 30 # Fixed height for now
    visualColor: '0xff0000' # Red
  abilities:
    - type: spawn_minions
      minionId: triangle_scout
      cooldownMs: 5000
      count: 3
